### ISSUE TITLE
Go to include on click

### ISSUE THREAD

**Issue by Chris2011** [rostanek/freemarker-support-for-netbeans#11]
When I do an include:

```
<#include "components/smth/smth.ftl" />
```

it would be nice to ctrl + click this file to navigate to it.

Regards

Chris

**Comment by rostanek** [comment]
I will add this feature in version 1.8.

**Comment by Chris2011** [comment]
Great thx :)

**Comment by Chris2011** [comment]
Tried it out, very nice feature. Thx :)
