### ISSUE TITLE
NB#241856 - IllegalArgumentException: Token id must not be null. Fix lexer org.htp.freemarkerfornetbeans.lexer.FreeMarkerLexer@35a2ebd2 

### ISSUE THREAD

**Issue by ralphbenjamin** [rostanek/freemarker-support-for-netbeans#14]
Issue from NetBeans' bugzilla

https://netbeans.org/bugzilla/show_bug.cgi?id=241856

**Comment by rostanek** [comment]
It seems that this bug is not related to my plugin, because it has different package: org.htp.freemarkerfornetbeans. Maybe someone tried to create such plugin 2 years ago...

**Comment by ralphbenjamin** [comment]
I'm sorry, I should've checked that before entering the issue.
