### ISSUE TITLE
Update needed for Netbeans 8.2

### ISSUE THREAD

**Issue by Git-GT** [rostanek/freemarker-support-for-netbeans#16]
Hi, could you update your plugin for Netbeans 8.2?
Thanks and best regards,

**Comment by rostanek** [comment]
I didn't noticed that it is already released. I will update it after I check if it is working fine with the new version.

**Comment by Git-GT** [comment]
Perfect thanks a lot!

**Comment by rostanek** [comment]
I checked that plugin works with version 8.2. I uploaded it to plugin portal, it will be available after verification.
