### ISSUE TITLE
Better icon than the red dot

### ISSUE THREAD

**Issue by skyghis** [rostanek/freemarker-support-for-netbeans#2]
It would be nice to replace the red icon with a better icon.

Based on the freemarker.org favicon I created an `svg` file and experted it to this 16x16 `png`:
![ftl-icon](https://cloud.githubusercontent.com/assets/1068552/9901455/23d31ec6-5c68-11e5-9efc-1ccba92e2fa3.png)

Contact me if you want the source `svg` file.

**Comment by skyghis** [comment]
After reflection I made a more Netbeans like icon : 
![ftl-icon](https://cloud.githubusercontent.com/assets/1068552/9905543/d34cb778-5c85-11e5-9327-3577e236a4c3.png)

**Comment by rostanek** [comment]
Thanks! I will use your icon in the next release.
