### ISSUE TITLE
understand @ftlvariable and provide completion from java types

### ISSUE THREAD

**Issue by mkleint** [rostanek/freemarker-support-for-netbeans#3]
eg for
[#-- @ftlvariable name="addedComment" type="com.atlassian.bamboo.comment.Comment" --]

**Comment by rostanek** [comment]
I don't recognize this keyword. Do you mean it should treat this comment as a hint for code completion?
Sounds interesting. Parsing content of comment should be easy, but completion of java types seems hard. I will see what I can do.

**Comment by mkleint** [comment]
i'm not sure myself how it works or how the standard is defined, googling around mostly leads me to intellij pages, most people at the office use it, so I assume it's somehow working and useful.

**Comment by rostanek** [comment]
I have managed to implement that type of code completion. You can check it in version 1.7 which I have released today. It should suggest fields of class defined in `type` attribute, but the class has to be in the same project.
