### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Simego** [rostanek/freemarker-support-for-netbeans#8]
I'm having trouble in the new version, really laggy, even while just typing, it lags when i do Ctrl+C, when select an area and type something, even while just typing random words fast.

The plugin is awesome by the way but this performance issue is really a problem, something related to the text validator maybe

**Comment by rostanek** [comment]
I have released new version of the plugin (1.7). It is available at NetBeans plugin portal from where you can download it. It will be also available in auto-update after verification. Check if the problem still occurs. On my machine I don't see any lags while typing or pasting code into editor.
Thanks for feedback.

**Comment by Simego** [comment]
it's really better now, no freezes while cuting/moving lines and typing.
awesome plugin btw :+1:

**Comment by rostanek** [comment]
Good to hear that. So I'm closing this issue.
Thanks! :blush:
